name: Build TheWay and publish it to release assets
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: If building the tag set Maven Version based on tag
        run: mvn --batch-mode versions:set -DnewVersion=${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags/')
      - name: Build Maven Package
        run: mvn --batch-mode package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release and upload asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/dcstheway-${{ github.ref_name }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}          
