name: Build TheWay and publish it to release assets
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Versions
        uses: actions/github-script@v6
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            var file_version = no_dash
            components = no_dash.split('.')
            console.log(no_dash)            
            for (let i = 0; i < (4 - components.lenght); i++)
              console.log(i)            
              file_version = file_version + '.0'
            console.log(file_version)            
            core.setOutput('tag', tag)
            core.setOutput('tag-no-v', no_v)
            core.setOutput('tag-no-dash', no_dash)
            core.setOutput('file-version', file_version)
        if: startsWith(github.ref, 'refs/tags/')
      - name: If building the tag set Maven Version based on tag
        run: mvn --batch-mode versions:set -DnewVersion="${{ steps.set_version.outputs.file-version }}"
        if: startsWith(github.ref, 'refs/tags/')
      - name: Build Maven Package
        run: mvn --batch-mode package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release and upload asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/dcstheway-${{ github.ref_name }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}          
